- hosts: localhost
  connection: local
  gather_facts: false 

  tasks:

  - name: accept weavescope port 4040
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 4040
      protocol: tcp
      jump: ACCEPT

  - name: accept conjur port 8080
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 8080
      protocol: tcp
      jump: ACCEPT

  - name: accept gitlab port 31080
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 31080
      protocol: tcp
      jump: ACCEPT
  - name: accept gitlab port 31443
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 31443
      protocol: tcp
      jump: ACCEPT
  - name: accept gitlab port 31022
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 31022
      protocol: tcp
      jump: ACCEPT

  - name: accept jenkins port 32080 
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 32080
      protocol: tcp
      jump: ACCEPT
  - name: accept jenkins port 32000
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 32000
      protocol: tcp
      jump: ACCEPT

  - name: accept artifactory port 33081
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 33081
      protocol: tcp
      jump: ACCEPT
  - name: accept artifactory port 33080
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 33080
      protocol: tcp
      jump: ACCEPT


  - name: accept securedemo 8099
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 8099
      protocol: tcp
      jump: ACCEPT


  - name: accept insecuredemo 8091
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 8091
      protocol: tcp
      jump: ACCEPT


